### ISSUE TITLE
关于相机参数的一些问题

### ISSUE THREAD

**Issue by crazydiamondaz** [DNA-Rendering/DNA-Rendering#7]
我使用了如下代码来读取数据：
![image](https://github.com/DNA-Rendering/DNA-Rendering/assets/46803604/0087dc1b-2fa0-4edf-bfc4-39edf58f11b6)
得到了如下相机参数：
![image](https://github.com/DNA-Rendering/DNA-Rendering/assets/46803604/8cd0489e-7154-49b4-abe8-65a57f286f58)
然后我使用了如下代码进行校正：
![image](https://github.com/DNA-Rendering/DNA-Rendering/assets/46803604/a63f94fd-d978-4e07-9a72-9b2ffb759d08)
得到的原始图片如下：

![00001](https://github.com/DNA-Rendering/DNA-Rendering/assets/46803604/45953f00-20c1-4268-ae7a-62e568bb15b9)
校正后的图像如下：
![output_image](https://github.com/DNA-Rendering/DNA-Rendering/assets/46803604/7def736e-46e3-4759-9310-710797ec5008)
我注意到D矩阵中的第五项值有点大。我采取的方式有什么问题吗？感谢作者的工作与对我错误的指正。

**Comment by DNA-Rendering** [comment]
Hi,

If you use our provided SMCReader to get the D value, I think there is nothing wrong.  The provided camera is based on OpenCV camera coordinate system, what you do to undistort the image by using "cv2.undistort" is reasonable.

**Comment by wchengad** [comment]
Hi @crazydiamondaz ,

For a very limited number of IDs in DNA-Rendering, the higher order distortion coefficient in some camera views might be large, but this does not indicate bad calibration. 

If you want to undistort and meanwhile want to eject the 'rings' for both image and mask, you can try the `cv2.getOptimalNewCameraMatrix` with `validPixROI=0` before undistort. Here is an example:

```
K, _ = cv2.getOptimalNewCameraMatrix(K_raw, D, (width,height), 0, (width,height), validPixROI=0, centerPrincipalPoint=False)
image = cv2.undistort(image, K_raw, D, None, K)
```

We did not give the official undistortion code, because it depends on your purpose. For another example of running [Gaussian splatting](https://github.com/graphdeco-inria/gaussian-splatting) in DNA-Rendering data like [4K4D](https://github.com/zju3dv/4K4D) which takes centered principle points, and you don't want to change the CUDA code, you can use the same process by `centerPrincipalPoint=True`.

**Comment by DNA-Rendering** [comment]
Hi @crazydiamondaz ,

Thank you for mentioning this issue. 

We have two sets of cameras, the one is RGB cameras, the other is kinect cameras. RGB camera's distortion coefficients are used to generate 3D keypoints and SMPLx parameters. For kinect camera's distortion coefficients, we suggest to use them in point-cloud generation, please check the provided script "_gen_pcd_from_kinect.py_".  

Since we mainly focused on human body region, the ring problem didn't bother us.  If you want to get rid of it, please check the [suggestions above](https://github.com/DNA-Rendering/DNA-Rendering/issues/7#issuecomment-1792359959).
